apiVersion: v1
kind: Secret
metadata:
  name: source-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://gitlab.com/abdelmoghit.idhsaine/Game-Streaming-Deployment.git
  password: glpat-WVqfrrypoyP4mFiWqh2m
  username: abdelmoghit.idhsaine