apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      imagePullSecrets:
      - name: dockerhubpull
      containers:
        - name: service
          image: prankster08/auth-image:hatim-949f829c
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: production
spec:
  selector:
    app: authservice
  ports:
    - port: 3001
      targetPort: 3001
