apiVersion: apps/v1
kind: Deployment
metadata:
  name: uiservice
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uiservice
  template:
    metadata:
      labels:
        app: uiservice
    spec:
      containers:
        - name: service
          image: prankster08/auth-image:abdelmoghit-39a61491
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: uiservice
  namespace: production
spec:
  selector:
    app: uiservice
  ports:
    - port: 3000
      targetPort: 3000
