apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels:
        app: ui-service
    spec:
      containers:
        - name: service
          image: prankster08/ui-image:hatim-949f829c
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: production
spec:
  selector:
    app: ui-service
  ports:
    - port: 3000
      targetPort: 3000
