apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jwt-disabled
  namespace: production
  annotations:
    konghq.com/strip-path: "false"

spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /api/auth/signup
            pathType: Prefix
            backend:
              service:
                name: authservice
                port:
                  number: 3001
          - path: /api/auth/signin
            pathType: Prefix
            backend:
              service:
                name: authservice
                port:
                  number: 3001
          - path: /api/auth/user
            pathType: Prefix
            backend:
              service:
                name: authservice
                port:
                  number: 3001
          - path: /api/auth/list
            pathType: Prefix
            backend:
              service:
                name: authservice
                port:
                  number: 3001
          - path: /api/auth/search
            pathType: Prefix
            backend:
              service:
                name: authservice
                port:
                  number: 3001
          - path: /api/auth/logout
            pathType: Prefix
            backend:
              service:
                name: authservice
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui-service
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jwt-enabled
  namespace: production
  annotations:
    konghq.com/strip-path: "false"
    konghq.com/plugins: app-jwt

spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /api/auth/update
            pathType: Prefix
            backend:
              service:
                name: authservice
                port:
                  number: 3001
          - path: /api/auth/delete
            pathType: Prefix
            backend:
              service:
                name: authservice
                port:
                  number: 3001